# Generated by Django 3.0.2 on 2020-01-30 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_no', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('complete', models.BooleanField(default=False)),
                ('grateful_1', models.CharField(max_length=1000)),
                ('grateful_2', models.CharField(max_length=1000)),
                ('grateful_3', models.CharField(max_length=1000)),
                ('good_deed', models.CharField(max_length=1000)),
                ('good_deed_impact', models.CharField(blank=True, max_length=1000)),
                ('adventure', models.CharField(max_length=1000)),
                ('adventure_completed', models.BooleanField(default=False)),
                ('improvement', models.CharField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('impact', models.CharField(blank=True, max_length=250)),
                ('goal_completed', models.BooleanField(default=False)),
                ('parent_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_items', to='diary.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('parent_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='diary.Entry')),
            ],
        ),
    ]
